name: ai_filter_flutter
description: Flutter version of AI Filter app for detecting AI-generated content

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase for backend
  supabase_flutter: ^2.5.6
  
  # File and image picking
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # HTTP requests
  http: ^1.1.0
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # App assets
  assets:
    - assets/images/
    - assets/icons/
  
  # App fonts (optional)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
